export const loadingItems = [
  {
    id: 1,
    price: -1,
    image: "loading",
    title: "loading",
    description: "loading",
    largeImage: "loading",
    brand: "loading",
    category: "loading",
    gender: "loading",
  },
  {
    id: 2,
    price: -1,
    image: "loading2",
    title: "loading2",
    description: "loading2",
    largeImage: "loading2",
    brand: "loading2",
    category: "loading2",
    gender: "loading2",
  },
  {
    id: 3,
    price: -1,
    image: "loading3",
    title: "loading3",
    description: "loading3",
    largeImage: "loading3",
    brand: "loading3",
    category: "loading3",
    gender: "loading3",
  },
  {
    id: 4,
    price: -1,
    image: "loading4",
    title: "loading4",
    description: "loading4",
    largeImage: "loading4",
    brand: "loading4",
    category: "loading4",
    gender: "loading4",
  },
  {
    id: 5,
    price: -1,
    image: "loading5",
    title: "loading5",
    description: "loading5",
    largeImage: "loading5",
    brand: "loading5",
    category: "loading5",
    gender: "loading5",
  },
];
